# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zeit ist relativ. Kostbar.
email: mephisztoe@live.de
description: >- # this means to ignore newlines until "baseurl:"
  Wie oft lernst Du jeden Tag etwas Neues und Du hattest bereits die verblüffende
  Erkenntnis, dass eine sich immer schneller drehende Welt praktisch täglich neue Innovationen
  bereithält. Geht mir auch so. Manchmal habe ich das Bedürfnis, solche Erkenntnisse
  aufzuschreiben. Mir hilft das und vielleicht hat mein externes Gedächtnis auch für Dich einen Nutzen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mephisztoe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mephisztoe
github_username:  mephisztoe

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

comments:
    enabled: true
    show_count: true
    receiver: https://jekyllcommentfunction.azurewebsites.net/api/PostComment

emptyArray: [] # Leave this here.

defaults: 
  -
    scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      author: mephisztoe
      commenting: open

authors:
  mephisztoe:
    name: Christian jacob
    email: mephisztoe@live.de
    url: https://mephisztoe.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
